version: '3.8'
services:
  mysql-docker:
    image: mysql:8.0
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockertestdb
    ports:
      - "3306:3306"

  spring-boot-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/dockertestdb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-docker
